name = "NumericalSuite"
uuid = "d9b88bdd-19fa-4f09-ad23-7848864feb24"
authors = ["Javier González Monge"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
