name = "NumericalSuite"
uuid = "d9b88bdd-19fa-4f09-ad23-7848864feb24"
authors = ["Javier González Monge"]
version = "0.1.0"

[deps]
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
UnPack = "1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
